### ISSUE TITLE
Cannot add version 0.0.7 on webjars from npm because of some required metadata missing

### ISSUE THREAD

**Issue by MRauca** [lttb/typed-styles#6]
![image](https://user-images.githubusercontent.com/29944588/58556520-e4c41500-8224-11e9-8449-3cdfa888b5b1.png)

**Comment by lttb** [comment]
Hi @MRauca!

Could you try to add `0.0.8` version please?
It was fixed in https://github.com/lttb/typed-styles/pull/4

**Comment by MRauca** [comment]
Yes, version 8.0.0 works indeed, but react-datepicker which depdends indirectly on this package requires version 0.0.7, and I cannot add it (Unresolved dependecy: org.webjars.npm#typed-styles;[0.0.7,0.0.8): not found). Maybe it's time to stop using webjars in our project.
